In [57]:
import pandas as pd
import numpy as np
import sklearn.metrics.pairwise as smp
import sklearn.metrics as sp
import scipy.stats as pear

In [38]:
X = [[0, 1], [1, 1],[3,2],[9,8],[12,7],[6,3],[7,4]];X


[[0, 1], [1, 1], [3, 2], [9, 8], [12, 7], [6, 3], [7, 4]]

# 1.Euclidean Distance Matrix
- Euclidean distance between two points is the length of the path connecting them

### By simple python

In [2]:
from math import sqrt
plot1 = [3,3]
plot2 = [5,4]
euclidean_distance = sqrt( (plot1[0]-plot2[0])**2 - (plot1[1]-plot2[1])**2 )
euclidean_distance

1.7320508075688772

### Using libraries

In [3]:
smp.euclidean_distances(X, X)

NameError: name 'smp' is not defined

In [40]:
smp.euclidean_distances(X, [[0, 0]])

array([[ 1.        ],
       [ 1.41421356],
       [ 3.60555128],
       [12.04159458],
       [13.89244399],
       [ 6.70820393],
       [ 8.06225775]])

# 2. Manhattan Distance Matrix
- It is a metric in which the distance between two points is the sum of the absolute differences between the x-coordinates and y-coordinates.
- In a plane with p1 at (x1, y1) and p2 at (x2, y2). Manhattan distance = |x1 – x2| + |y1 – y2|

### By simple python

In [4]:
manhattan_distance = ( abs(plot1[0]-plot2[0]) + abs(plot1[1]-plot2[1]) )
manhattan_distance

3

### By using libraries

In [67]:
smp.manhattan_distances(X,X)

array([[ 0.,  1.,  4., 16., 18.,  8., 10.],
       [ 1.,  0.,  3., 15., 17.,  7.,  9.],
       [ 4.,  3.,  0., 12., 14.,  4.,  6.],
       [16., 15., 12.,  0.,  4.,  8.,  6.],
       [18., 17., 14.,  4.,  0., 10.,  8.],
       [ 8.,  7.,  4.,  8., 10.,  0.,  2.],
       [10.,  9.,  6.,  6.,  8.,  2.,  0.]])

In [42]:
smp.manhattan_distances(X,[[0,0]])

array([[ 1.],
       [ 2.],
       [ 5.],
       [17.],
       [19.],
       [ 9.],
       [11.]])

# 3. Mahanalobis Distance Matrix

In [75]:
from scipy.spatial.distance import cdist

A = [[1, 2],  
     [2, 1]]

B = [[1, 1],
     [2, 2],
     [1, 3],
     [1, 4]]
out = cdist(A, B, metric='cityblock');out

array([[1., 1., 1., 2.],
       [1., 1., 3., 4.]])

# 4. Jaccard distance

In [68]:
y_pred = [14, 5, 1, 93, 43, 52, 17]
y_true = [40, 1, 20, 33, 69, 96, 100]
sp.jaccard_similarity_score(y_pred=y_pred, y_true=y_true)

0.0

In [69]:
sp.jaccard_similarity_score(y_pred=[11,13], y_true=[13,9])

0.0

In [70]:
y_pred = [0, 2, 1, 3, 4, 5, 7]
y_true = [0, 1, 2, 3, 6, 9, 10]
sp.jaccard_similarity_score(y_pred=y_pred, y_true=y_true)

0.2857142857142857

In [71]:
sp.jaccard_similarity_score(y_pred=[11,13], y_true=[11,13])

1.0

In [72]:
sp.jaccard_similarity_score(y_pred=[1,2,3,4,5], y_true=[4,5,6,7,8])

0.0

In [73]:
sp.jaccard_similarity_score(y_pred=[11,13,15,17], y_true=[11,12,13,14])

0.25

# 5. Cosine distance

In [52]:
x = np.array([6,3,10,13,42,53])
y = np.array([5,3,2,10,7,42])
x = x.reshape(1,-1)
y = y.reshape(1,-1)
x = sp.pairwise.cosine_similarity(x,y);x


array([[0.87732237]])

In [54]:

x = np.array([2,3,1,0,2,3])
y = np.array([2,3,0,0,0,1])

x = x.reshape(1,-1)
y = y.reshape(1,-1)


x = sp.pairwise.cosine_similarity(x,y)
x

array([[0.8229512]])

In [55]:
x = np.array([2,1,0,3,1])
y = np.array([2,3,1,3,1])

x = x.reshape(1,-1)
y = y.reshape(1,-1)


x = sp.pairwise.cosine_similarity(x,y)
x

array([[0.89597867]])

In [59]:
x = np.array([2,3,1,0,2,3])
y = np.array([3,2,0,1,3,2])

x = x.reshape(1,-1)
y = y.reshape(1,-1)


x = sp.pairwise.cosine_similarity(x,y)
x

array([[0.88888889]])

In [60]:
x = np.array([2,3,1,0,2,3])
y = np.array([3,1,0,1,2,1])

x = x.reshape(1,-1)
y = y.reshape(1,-1)


x = sp.pairwise.cosine_similarity(x,y)
x

array([[0.76980036]])

In [61]:
x = np.array([2,3,1,0,2,3])
y = np.array([2,3,1,0,2,3])

x = x.reshape(1,-1)
y = y.reshape(1,-1)


x = sp.pairwise.cosine_similarity(x,y)
x

array([[1.]])

# 6. Pearson coefficient

In [58]:
x = [1, 2, 3, 4, 5]
corr = [2, 4, 6, 8, 10]
corr, p_value = pear.pearsonr(x, corr)

corr

1.0

In [62]:
pear.pearsonr([1,2,3,4],[3,4,2,1])

(-0.8, 0.19999999999999993)

In [63]:
pear.pearsonr([0,1,2], [0,1,2])

(1.0, 0.0)

In [64]:
pear.pearsonr([1,8], [8,1])


(-1.0, 0.0)

In [65]:
pear.pearsonr([1,2,4,5], [4,5,2,1])


(-0.9, 0.09999999999999999)

In [66]:
pear.pearsonr([9,7,8,3],[3,7,8,3])


(0.3493975903614458, 0.6506024096385541)